### ISSUE TITLE
Instructions on discovering memory offset?

### ISSUE THREAD

**Issue by skorokithakis** [Darkman802/Super-Hexagon-Bot#2]
This is fantastic work, I would like to replicate this for one of my projects, but I'm running Linux, and trying to figure it out for that is more fun than just booting to Windows and using this script. Can I ask how you found the memory location and values that you've hardcoded into the script?

**Comment by Darkman** [comment]
I apologize for it being two months, I never got an email about the issue you created and only saw it because I was randomly looking at my repos.

As for your question (if you still even need an answer), take a look at this [thread](https://github.com/zku/SuperHaxagon/issues/1) for a discussion about it. You could probably use Cheat Engine to narrow down the addresses if they aren't the same for you.

**Comment by skorokithakis** [comment]
Thank you, I eventually saw that and tried for a few hours to reproduce the findings, with not much success. I will disable ASLR on linux and try again, thanks.
